### ISSUE TITLE
creating a new image, uncheck rebuild, errors

### ISSUE THREAD

**Issue by jhujasonw** [mprov-ng/mprov_control_center#103]

**Comment by jhujasonw** [comment]
```
Environment:


Request Method: POST
Request URL: http://mprov-ai.arch.jhu.edu/admin/systems/systemimage/add/

Django Version: 3.2.22
Python Version: 3.8.16
Installed Applications:
['jazzmin',
 'django_filters',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'networks',
 'osmanagement',
 'systems',
 'jobqueue',
 'scripts',
 'disklayouts',
 'rest_framework',
 'rest_framework_api_key',
 'dbbackup',
 'utils',
 'mprov_ldap_manager']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django_session_timeout.middleware.SessionTimeoutMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/var/www/mprov_control_center/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/www/mprov_control_center/lib64/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/mprov_control_center/lib64/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/var/www/mprov_control_center/lib64/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/var/www/mprov_control_center/lib64/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/mprov_control_center/lib64/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/var/www/mprov_control_center/lib64/python3.8/site-packages/django/contrib/admin/options.py", line 1657, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/var/www/mprov_control_center/lib64/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/var/www/mprov_control_center/lib64/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/var/www/mprov_control_center/lib64/python3.8/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/var/www/mprov_control_center/lib64/python3.8/site-packages/django/contrib/admin/options.py", line 1591, in _changeform_view
    return self.response_add(request, new_object)
  File "/var/www/mprov_control_center/lib64/python3.8/site-packages/django/contrib/admin/options.py", line 1182, in response_add
    obj_url = reverse(
  File "/var/www/mprov_control_center/lib64/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/var/www/mprov_control_center/lib64/python3.8/site-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)

Exception Type: NoReverseMatch at /admin/systems/systemimage/add/
Exception Value: Reverse for 'systems_systemimage_change' with arguments '('',)' not found. 1 pattern(s) tried: ['admin/systems/systemimage/(?P<object_id>.+)/change/\\Z']
```
